### ISSUE TITLE
crash on calibrate

### ISSUE THREAD

**Issue by willwade** [AceCentre/EyeCommander#21]
So calibrate - works fine - but once its done and goes back to recognising - this SOMETIMES happens..

See video: See video https://vimeo.com/608845527

```
Epoch 7/7
180/180 [==============================] - 4s 22ms/step - loss: 0.1320 - accuracy: 0.9556
calibration successful
[ WARN:0] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-sn_xpupm\opencv\modules\videoio\src\cap_msmf.cpp (1022) CvCapture_MSMF::grabFrame videoio(MSMF): can't grab frame. Error: -1072873821
Traceback (most recent call last):
  File "C:\GitHub\EyeCommander\eyecommand.py", line 37, in <module>
    eyecommand()
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\GitHub\EyeCommander\eyecommand.py", line 33, in eyecommand
    eyecommander.run()
  File "C:\GitHub\EyeCommander\eye_commander\commander\commander.py", line 166, in run
    display.display_prediction(label=label_state, frame=frame)
  File "C:\GitHub\EyeCommander\eye_commander\display_tools\display.py", line 38, in display_prediction
    h, w = np.shape(frame)[:2]
ValueError: not enough values to unpack (expected 2, got 0)
[ WARN:0] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-sn_xpupm\opencv\modules\videoio\src\cap_msmf.cpp (438) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback
[ WARN:0] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-sn_xpupm\opencv\modules\videoio\src\cap_msmf.cpp (438) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback
```

**Comment by gavinhenderson** [comment]
This is no longer relevant to the electron build
